#docker-compose -f xxxxx.yml up -d

version: '2'
services:
  web:
    image: liliangbin/sandbox:v1
    privileged: true
    command: ./run.sh
    ports:
      - "8080:8080"
    volumes:
      - /root/static/video:/flask-sandbox/app/static/video
      - /root/static/image:/flask-sandbox/app/static/image
      - /root/static/document:/flask-sandbox/app/static/document