#docker-compose -f xxxxx.yml up -d

version: '2'
services:
  web:
    image: liliangbin/sandbox:v2
    privileged: true
    command: ls /data
    ports:
      - "5050:5050"
      - "8080:8080"
    volumes:
      - ../app/static/video:/flask-sandbox/app/static/video
      - ../app/static/image:/flask-sandbox/app/static/image
      - ../app/static/document:/flask-sandbox/app/static/document
      - /E/python/steam:/data
    restart: always
